spring.application.name=admin_usuarios_mongodb_t4
spring.mongodb.uri=mongodb://localhost:27017/admin_usuarios_t4
server.port=8090

debug=true
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG

