spring.application.name=1_intento_certamen2023
spring.mongodb.uri=mongodb://localhost:27017/1_intento_certamen2023
server.port=8090

debug=true
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.mongodb.driver=DEBUG

